networks:
  backend:

services:
  web:
    image: nginx:1.25-alpine3.17
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ./:/www:rw
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/logs/nginx:/var/logs/nginx:rw
    depends_on:
      - app
    networks:
      - backend

  app:
    image: rcsnjszg/backend2024
    build:
      context: ./docker/php/alpine/
      dockerfile: Dockerfile
    volumes:
      - ./:/www:rw
    networks:
      - backend

  mongo:
      image: mongo
      restart: always
      ports:
          - 27017:27017
      environment:
          MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
          MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
          MONGODB_CONNSTRING: ${MONGO_CONNECTION_STRING}
      volumes:
          - ./docker/mongodb:/data/db
      networks:
          - backend
      command: mongod --auth --bind_ip_all
